# Spring application settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

# Thymeleaf settings
# These settings are optional and can be adjusted based on your requirements
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false

# Logging settings
logging:
  level:
    root: INFO

# Server settings
server:
  port: 8080
